config/routes.rb
Rails.application.routes.draw do
  get 'expenses/index'
  get 'expenses/new'
  # get "/home/index"
  resources :groups do
    resources :expenses, only: [:index, :new, :create]
  end
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root_path
    end
    unauthenticated do
      root "home#index", as: :unauthenticated_root_path
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user

  has_many :expense_groups
  has_many :groups, through: :expense_groups

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/expense_group.rb
class ExpenseGroup < ApplicationRecord
  belongs_to :expense
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :expense_groups, dependent: :destroy
  has_many :expenses, through: :expense_groups, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :expenses

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_group

  def index
    @expenses = @group.expenses.order(created_at: :desc)
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    @expense.group_id = @group.id
    if @expense.save
      @expense_group = ExpenseGroup.create(group: @group, expense: @expense)
      redirect_to group_expenses_path(@group), notice: 'Expense was successfully created.'
    else
      puts @expense.errors.full_messages
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'group was successfully created.'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  def index
    return unless user_signed_in?

    redirect_to groups_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" >
  <div class="d-flex justify-content-between align-items-center border border-secondary-subtle w-100  p-2 mt-2">
    <div class='text-decoration-none d-flex mr-4 w-75 align-items-center gap-3 '>
      <div class="d-flex flex-column ">
        <p class=""><%= expense.name %></p>
        <p class="my-0"><%= expense.created_at.strftime('%b %d, %Y') %></p>
      </div>
  
   </div>

    <div class=" d-flex flex-column justify-content-between">

      <p class=""><strong><%= "$#{expense.amount}" %></strong></p>
    </div>
  </div>
</div>

app/views/expenses/index.html.erb
<section>
  <% if current_user %>
		<%= render 'layouts/expenses_header' %>
  <% end %>
  <div class="d-flex gap-2 justify-content-between align-items-center border border-secondary-subtle   p-2 mt-2 mx-2 bg-white">
		<div>
			<%= image_tag "#{@group.icon}", :class => 'img-fluid img-thumbnail w-25' %>
		</div>
		<div class="expense-group d-flex gap-2">
			<p> <%="#{@group.name}: "%> </p>
			<p style="font-weight:bold"><%= "$#{ @group.expenses.sum(:amount) }" %></p>
    </div>
  </div>

	<div id="expenses" class="px-2 bg-white">
    <% @expenses.each do |expense| %>
      <%= render expense %>
    <% end %>
  </div>
	<div class="d-flex flex-column fixed-bottom align-items-center justify-content-center text-center w-100 p-3" style="background-color: #5fb523;">
		<%= link_to 'Add a new expense', new_group_expense_path(@group), class: "text-white w-100  nav-link border border-white  p-2"  %>
	</div>
</section>

app/views/expenses/new.html.erb
<div>
  <%= link_to group_expenses_path(@group), :class => "return-icon" do %>
  <% end %>
</div>
<%= form_with model: @expense, url: group_expenses_path(@group) do |form| %>
	<header class="bg-primary text-white p-2">
    <nav class="d-flex justify-content-between align-items-center text-center">
			<%= link_to group_expenses_path do %>
				<i class="fas fa-arrow-left fs-1 text-white"></i>
			<span class="sr-only"></span>
			<% end %>
			<h2 class="m-0 p-0">New expense</h2>
			<%= form.submit "Save", class: "nav-link fs-2" %>
    </nav>
  </header>
  <div class=m-3>
    <div class="mb-3">
      <%= form.label :name, style: "display: block", class:"form-label"%>
      <%= form.text_field :name, :required => true, :maxlength => "12",type:"text",class:"form-control",id:"formGroupExampleInput",placeholder:"Expense name"%>
    </div>
    <div class="mb-3">
      <%= form.label :amount, style: "display: block", class:"form-label" %>
      <%= form.number_field :amount, :required => true, :maxlength => "12",type:"text",class:"form-control",id:"formGroupExampleInput",placeholder:"Amount"%>
    </div>
		<div class="mb-3">
			<%= form.label 'Select a Category', class: 'fs-5 mb-2' %>
				<%= form.select :icon, options_for_select([
					['Education','education.png'],
					['Entertainment','entertainment.png'],
					['Food', 'food.png'],
					['Hospital','hospital.png'],
					['House','house.png'],
					['Personal Care','personal_care.png'],
					['Saving','saving.png'],
					['Transportation','travel.png'],
					['Utilities','utilities.png']
				]), {}, class:'form-select mb-4', id: 'icon', aria_label: "form-select category" %>
		</div>
  <div>

<% end %>

app/views/groups/index.html.erb
<%# <h1>Your Categories</h1> %>
	<% if current_user %>
		<%= render 'layouts/groups_header' %>
	<% end %>

    <% @groups.each do |group| %>
			<%= link_to group_path(group), class: "text-decoration-none text-dark" do %>
			<div id="<%= dom_id group %>" class="px-2">
				<div class="d-flex justify-content-between align-items-center border border-secondary-subtle p-2 mt-2 bg-white">
					<%= link_to  group_expenses_path(group), class:'text-decoration-none d-flex align-items-center gap-3', style:"color:#434b54"  do %>
						<%= image_tag group.icon, :class => 'img-fluid img-thumbnail w-25', :alt => "#{group.name} icon" %>
						<div class="d-flex flex-column">
							<p class=""><%= group.name %></p>
							<p class="my-0"><%= group.created_at.strftime('%b %d, %Y') %></p>
						</div>
					<% end %>

					<div class=" d-flex flex-column justify-content-between">
						<p class=""><strong><%= " $#{group.expenses.sum(:amount)}"%></strong></p>
					</div>
				</div>
			</div>
		<% end %>
	<% end %>

<div class="d-flex flex-column fixed-bottom align-items-center justify-content-center text-center w-100 p-3" style="background-color: #5fb523;">
	<%= link_to 'Add a new category', new_group_path, class: "text-white w-100  nav-link border border-white  p-2" %>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">

<%= form_with(model: @group, local: true) do |form| %>
	<header class="text-white p-2" style="background: #3778c2">
    <nav class="d-flex justify-content-between align-items-center text-center">
			<%= link_to groups_path do %>
				<i class="fas fa-arrow-left fs-1 text-white"></i>
				<span class="sr-only"></span>
			<% end %>
			<h2 class="m-0 p-0">New Category</h2>
			<%= form.submit "Save", class: "nav-link fs-2" %>
    </nav>
  </header>
	<% if @group.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

			<ul>
				<% @group.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


	<div class='container py-4'>
		<div class='container w-70'>
		<%= form.label 'Select a Category', class: 'fs-5 mb-2' %>
				<%= form.select :icon, options_for_select([
					['Education','education.png'],
					['Entertainment','entertainment.png'],
					['Food', 'food.png'],
					['Hospital','hospital.png'],
					['House','house.png'],
					['Personal Care','personal_care.png'],
					['Saving','saving.png'],
					['Transportation','travel.png'],
					['Utilities','utilities.png']
				]), {}, class:'form-select mb-4', id: 'icon', aria_label: "form-select category" %>
			
				<%= form.hidden_field :user_id, value: current_user.id %>
					<div>
						<%= form.label :name %>
						<%= form.text_field :name, class: 'form-control' %>
					</div>

		</div>
	</div>
<% end %>

app/views/home/index.html.erb
<section class = " d-flex flex-column align-items-center">
	<div class=" d-flex flex-column justify-content-center"  style="height: 500px;">
		<h1 class="">ExpenseApp</h1>
	</div>
	<div class="d-flex flex-column fixed-bottom align-items-center justify-content-center text-center p-3">
		<%= link_to 'Log in', new_user_session_path, class: "text-white w-100 p-3 nav-link", style: "background: #3778c2"  %>
		<%= link_to 'Sign up', new_user_registration_path,  class: "nav-link p-3 w-100" %>
	</div>
</section>

app/views/layouts/_expenses_header.html.erb
<header class="text-white sticky-top" style="background: #3778c2">
	<nav class="d-flex justify-content-between align-items-center text-center p-2">
		<%= link_to groups_path do %>
			<i class="fas fa-arrow-left fs-1 text-white"></i>
			<span class="sr-only"></span>
    <% end %>

    <h2 class="m-0 p-0">EXPENSES</h2>
 		<i class="fa-solid fa-magnifying-glass text-white fs-1"></i>
	</nav>
</header>

app/views/layouts/_groups_header.html.erb
<header class="text-white sticky-top" style="background: #3778c2">
	<nav class="d-flex justify-content-between align-items-center text-center p-2">
		<a class="btn" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
			<i class="fa-solid fa-bars" style="font-size: 24px; width: 32px; height: 32px; color:white;"></i>
		</a>

		<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
			<div class="offcanvas-header">
				<h5 class="offcanvas-title" id="offcanvasExampleLabel">Expense App</h5>
				<button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
			</div>
			<div class="offcanvas-body">
				<div>
					This is a  mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what.
				</div>
				<div class="dropdown mt-3">
					<button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
						Dropdown button
					</button>
					<ul class="dropdown-menu">
						<li><%= link_to "Categories", groups_path, class: "w-100  nav-link border border-white dropdown-item  p-2" %></li>
						<li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "w-100  nav-link border border-danger dropdown-item  p-2" %></li>
					</ul>
				</div>
			</div>
		</div>
		<h2 class="m-0 p-0">CATEGORIES</h2>
		<i class="fa-solid fa-magnifying-glass text-white fs-1"></i>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fraunces&display=swap" rel="stylesheet"> 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200;0,6..12,300;0,6..12,400;0,6..12,500;0,6..12,600;0,6..12,700;0,6..12,800;0,6..12,900;0,6..12,1000;1,6..12,200;1,6..12,300;1,6..12,400;1,6..12,500;1,6..12,600;1,6..12,700;1,6..12,800;1,6..12,900;1,6..12,1000&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/777c04cd40.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>